cache: pip
language: python
os: linux

services:
    - redis

jobs:
  include:
    - python: 3.7
    - python: 3.6
    - python: 3.8

install:
  - pip install poetry
  - poetry install
  - pip list

script:
  - echo "$TRAVIS_PYTHON_VERSION"
  - pytest tests/cli_tests
