name: Release
on: [push]
  # push:
  #   - master
  # tags:
  #   - v*

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-16.04

    # FIXME
    # help test shouldn't depends on this to run
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      env:
        PASSWORD: ${{ secrets.PYPI_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -U pip
          pip install poetry
          poetry install
          python -c "import sys; print(sys.version)"
          pip list
      - name: Poetry Build
        run: |
          . venv/bin/activate
          poetry build
      - name: Test Build
        run: |
          python3 -m venv fresh_env
          . fresh_env/bin/activate
          pip install dist/*.whl

          iredis -h
          iredis help GET

      - name: Upload to Pypi
        run: poetry publish --username __token__ --password ${PASSWORD}
