name: Greet Everyone
on: [push]

jobs:
  test:
    name: Pytest
    strategy:
      matrix:
        os: [ubuntu-16.04]
        python: ['3.7']
    runs-on: ${{ matrix.os }}

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          apt-get install python3-venv
          python3 -m venv venv
          . venv/bin/activate
          pip install poetry pip==19
          poetry install
          python -c "import sys; print(sys.version)"
          pip list
      - name: Pytest
        run: |
          . venv/bin/activate
          pytest
