name: Greet Everyone
on: [push]

jobs:
  test:
    name: Pytest
    matrix:
      os: [ubuntu-latest, ubuntu-16.04]
      python: ['3.6', '3.7', '3.8']
    runs-on: ${{ matrix.os }}

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Setup Redis Server.
        uses: supercharge/redis-github-action@1.1.0
      - name: Install Dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install poetry pip==19
          poetry install
      - name: Pytest
        run: |
          . venv/bin/activate
          pytest
